Update run scripts. Re-format files

diff --git a/vpn/brook/run b/vpn/brook/run
--- a/vpn/brook/run
+++ b/vpn/brook/run
@@ -1,11 +1,11 @@
 #!/bin/bash
-if [ ! -r /vpn/vpn.config ] ; then
-        echo "Could not load config file from /vpn/vpn.config. Please check your volume config" 1>&2
-        exit 1
+
+if [ ! -r /vpn/vpn.config ]; then
+  echo "Could not load config file from /vpn/vpn.config. Please check your volume config" 1>&2
+  exit 1
 fi
 
 source /vpn/vpn.config
-
 
 if [ -z "$SERVER" ]; then
   echo "No server is set. Exiting."
@@ -14,7 +14,7 @@ fi
 
 if [ -z "$USERNAME" ]; then
   echo "No username is set. Exiting."
-  exit 1 
+  exit 1
 fi
 
 if [ -z "$PASSWORD1" ]; then
@@ -37,14 +37,17 @@ gw=$(ip route | awk '/default/ {print $3}')
 ip route add to ${LOCAL_NETWORK} via $gw dev eth0
 
 echo Running openconnect
-(echo -e "${PASSWORD1}\n${PASSWORD2}"; read -s) | openconnect ${SERVER} --passwd-on-stdin --no-dtls -b -u ${USERNAME}
+(
+  echo -e "${PASSWORD1}\n${PASSWORD2}"
+  read -s
+) | openconnect ${SERVER} --passwd-on-stdin --no-dtls -b -u ${USERNAME}
 sleep 3
 
 # start
-if [[ -n "$SUSERNAME" -a -n "$SPASSWORD" ]]; then
+if [[ -n "$SUSERNAME" && -n "$SPASSWORD" ]]; then
   echo "Running brook with authentication"
-  brook socks5 --socks5 0.0.0.0:${PROXY_PORT} --username ${SUSERNAME} --password ${SPASSWORD} &> /dev/null
+  brook socks5 --socks5 0.0.0.0:${PROXY_PORT} --username ${SUSERNAME} --password ${SPASSWORD} &>/dev/null
 else
   echo "Running brook without authentication"
-  brook socks5 --socks5 0.0.0.0:${PROXY_PORT} &> /dev/null
+  brook socks5 --socks5 0.0.0.0:${PROXY_PORT} &>/dev/null
 fi
